<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\OrionERP.Application\OrionERP.Application.csproj" />
    <ProjectReference Include="..\OrionERP.Infrastructure\OrionERP.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>01c9196d-6f55-412a-a5a3-4f7a68cfcc8c</UserSecretsId>
    <NoWarn>$(NoWarn);NU1510</NoWarn>
  </PropertyGroup>

</Project>
