<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\OrionERP.Application\OrionERP.Application.csproj" />
    <ProjectReference Include="..\OrionERP.Infrastructure\OrionERP.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.0" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4d230f77-7169-4ecb-9189-7be2c7932110</UserSecretsId>
    <NoWarn>$(NoWarn);NU1510</NoWarn>
  </PropertyGroup>

</Project>
