IF COL_LENGTH('dbo.RESERVATION', 'SUITE_DISCOUNT_PERCENT') IS NULL
BEGIN
    ALTER TABLE dbo.RESERVATION
    ADD SUITE_DISCOUNT_PERCENT decimal(5,2) NOT NULL
        CONSTRAINT DF_RESERVATION_SUITE_DISCOUNT_PERCENT DEFAULT (0);
END;
