IF OBJECT_ID('dbo.ROOM_CALENDAR_OUTLOOK_SYNC', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.ROOM_CALENDAR_OUTLOOK_SYNC
    (
        ID int IDENTITY(1,1) NOT NULL CONSTRAINT PK_ROOM_CALENDAR_OUTLOOK_SYNC PRIMARY KEY,
        SOURCE_KEY nvarchar(200) NOT NULL,
        ROOM_NAME varchar(50) NOT NULL,
        RESERVATION_ID int NULL,
        START_DATE date NOT NULL,
        END_DATE_EXCLUSIVE date NOT NULL,
        OUTLOOK_CALENDAR_ID nvarchar(512) NOT NULL,
        OUTLOOK_EVENT_ID nvarchar(512) NOT NULL,
        CONTENT_HASH char(64) NOT NULL,
        LAST_SYNCED_UTC datetime2(0) NOT NULL CONSTRAINT DF_ROOM_CALENDAR_OUTLOOK_SYNC_LAST_SYNCED_UTC DEFAULT SYSUTCDATETIME()
    );

    CREATE UNIQUE INDEX UX_ROOM_CALENDAR_OUTLOOK_SYNC_SOURCE_CALENDAR
        ON dbo.ROOM_CALENDAR_OUTLOOK_SYNC (SOURCE_KEY, OUTLOOK_CALENDAR_ID);

    CREATE UNIQUE INDEX UX_ROOM_CALENDAR_OUTLOOK_SYNC_CALENDAR_EVENT
        ON dbo.ROOM_CALENDAR_OUTLOOK_SYNC (OUTLOOK_CALENDAR_ID, OUTLOOK_EVENT_ID);

    CREATE INDEX IX_ROOM_CALENDAR_OUTLOOK_SYNC_ROOM_DATES
        ON dbo.ROOM_CALENDAR_OUTLOOK_SYNC (ROOM_NAME, START_DATE, END_DATE_EXCLUSIVE);
END;
