SET XACT_ABORT ON;
BEGIN TRAN;

DECLARE @QuoteReservations TABLE
(
    ID int NOT NULL PRIMARY KEY
);

INSERT INTO @QuoteReservations (ID)
SELECT r.ID
FROM dbo.RESERVATION r
INNER JOIN dbo.Clientes c
  ON c.ID = r.CLIENTE_ID
WHERE UPPER(LTRIM(RTRIM(ISNULL(c.Nombre, '')))) COLLATE Latin1_General_100_CI_AI LIKE N'%COTIZAC%'
  AND UPPER(LTRIM(RTRIM(ISNULL(r.STATUS, '')))) COLLATE Latin1_General_100_CI_AI NOT IN
      (N'PAGADA', N'CANCELADA', N'CANCELADO');

UPDATE r
SET STATUS = 'COTIZACION'
FROM dbo.RESERVATION r
INNER JOIN @QuoteReservations q
  ON q.ID = r.ID;

UPDATE rc
SET STATUS = 'COTIZACION'
FROM dbo.ROOM_CALENDAR rc
INNER JOIN @QuoteReservations q
  ON q.ID = TRY_CAST(rc.LOCK_DESCRIPTION AS int)
WHERE ISNULL(rc.IS_LOCKED, 0) = 1;

COMMIT;
