SET XACT_ABORT ON;
BEGIN TRAN;

UPDATE rc
SET
    IS_LOCKED = 0,
    LOCKED_BY = '',
    LOCK_DESCRIPTION = '',
    STATUS = ''
FROM dbo.ROOM_CALENDAR rc
LEFT JOIN dbo.RESERVATION r
  ON r.ID = TRY_CAST(rc.LOCK_DESCRIPTION AS int)
WHERE rc.IS_LOCKED = 1
  AND TRY_CAST(rc.LOCK_DESCRIPTION AS int) IS NOT NULL
  AND r.ID IS NULL;

IF NOT EXISTS (
    SELECT 1
    FROM sys.key_constraints kc
    WHERE kc.parent_object_id = OBJECT_ID('dbo.ROOM_CALENDAR')
      AND kc.[type] = 'UQ'
      AND kc.name = 'UQ_ROOM_CALENDAR_ROOM_ROOM_DATE'
)
BEGIN
    ALTER TABLE dbo.ROOM_CALENDAR
    ADD CONSTRAINT UQ_ROOM_CALENDAR_ROOM_ROOM_DATE
        UNIQUE (ROOM, ROOM_DATE);
END;

COMMIT;
