<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\OrionERP.Application\OrionERP.Application.csproj" />
    <ProjectReference Include="..\OrionERP.Infrastructure\OrionERP.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.2.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>69745113-6b83-4911-8ef8-2296396806a2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
  <ProjectReference Include="..\OrionERP.Infrastructure\OrionERP.Infrastructure.csproj" />
  <ProjectReference Include="..\..\..\SatMassiveDownload\SatMassiveDownload\Sat.MassiveDownload.csproj" />
</ItemGroup>


</Project>
