# .github/workflows/ci.yml
name: ci
on: [push, pull_request]
jobs:
  build_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # optional; remove if you don't need full history
          submodules: false
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - run: dotnet restore OrionERP.sln
      - run: dotnet build OrionERP.sln --no-restore -c Release
      - run: dotnet test OrionERP.sln --no-build -c Release --logger "trx;LogFileName=test_results.trx"
      - name: List workspace
        shell: pwsh
        run: 'Get-ChildItem -Depth 2 | Select FullName'
