name: ci
on: [push, pull_request]
jobs:
  build_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - run: dotnet restore OrionERP.sln
      - run: dotnet build OrionERP.sln --no-restore -c Release
      - run: dotnet test  OrionERP.sln --no-build -c Release --logger "trx;LogFileName=test_results.trx"
